server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: eureka-server
logging:
  file:
    path: ./logs/${spring.application.name}
    name: ${spring.application.name}
